id: P3B0BB0B9
initial_creation_type: input
source_metadata:
  title: Fasting Ritual Series
  language: en
  description: 'Texts related to the two-day ritual of fasting and silence known in
    Tibetan as Nyungné (smyung gnas):'
  volume:
    fbaac8e439ab46808afd65b9ef43d7c5:
      title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
      parent: Practices
created_at: '2022-03-01T03:40:48.589703'
last_modified_at: '2022-03-01T03:40:48.589709'
